### ISSUE TITLE
Can we use it to develop in Laravel?

### ISSUE THREAD

**Issue by ImBIOS** [v-je/docker#4]
I need to develop in Laravel and I think it is not efficient to run composer with docker-compose every time with its subdirectory argument

**Comment by TRPB** [comment]
It maps to a directory on your computer so you can install libraries composer into the folder as any other environment.

**Comment by ImBIOS** [comment]
I need your recommendation on:
1. is it better for me to use Composer on Windows, or on WSL2? or is it better to use Laravel-Sail to try to learn Laravel for the first time?
2. Should I put the project directory in Windows or WSL2 directory?

**Comment by TRPB** [comment]
1. It doesn't matter. I built this for the lab machines where I work (I teach at a university) and it was easier to package all the software together. If you have composer installed natively you can use that for a shorter command.

1a. I don't use Laravel so can't comment on Sail, however you can install Laravel to the public directory.

2.  WSL2 directories are faster, but obviously requires a few more steps to access from an editor and not all editors can access the code easily  (you'll also need to tweak docker-compose.yml so the websites directory isn't mounted). It also removes any portability, with WSL2 directories you can just copy the entire folder to another machine, run `docker compose up` and the website works as-is. That's not the case with a directory inside WSL2 directly.

I'll note that other than testing it works on Windows I haven't spent any time developing a real application there as I don't use it However, apparently in Windows 11, a lot of the performance issues with mounted volumes are solved, though I haven't tried it myself.

**Comment by ImBIOS** [comment]
Thank you for the answer 👍
