### ISSUE TITLE
v.je page not loading "Can't reach page"

### ISSUE THREAD

**Issue by TShermz** [v-je/docker#6]
After downloading configuration files and running "docker compose up -d", v.je does not load within browser. I had it working a few days ago and continued on with Ch. 4 (MySQL), but will not load with existing folders or freshly re-created folders. NGINX can be accessed through in port 80 when running.

Specifically in Docker, landingpage-1 and updatecerts-1 fail to start with landingpage displaying the following error: 

fatal: destination path '/websites/default/public' already exists and is not an empty directory.

**Comment by TRPB** [comment]
The error won't matter, as it intentionally only runs the first time. Firstly, make sure you don't have any other web servers running and stop everything you have running from inside docker.

When you say "does not load", what exactly happens? 

If you run `ping v.je` does it come back with a response from 127.0.0.1?

**Comment by TShermz** [comment]
When inputting v.je into the browser, I receive "This site can't be reached" on Chrome along with "DNS_PROBE_FINISHED_NXDOMAIN"

Running ping v.je, I receive: `Ping request could not find host v.je. Please check the name and try again.`

In Docker, I have 5/7 containers running (maildev, mysql, php, databaseimportexport, and web) and nothing else. Port 80 takes me to a page that says, "Welcome to nginx!"

I can send screenshots of Docker, webpages, or folder if that'd be helpful.

**Comment by TShermz** [comment]
v.je can be reached in the browser and pinged on internet at work but cannot be reached/pinged on my home network.

UPDATE: Turns out it was the DNS settings with my wifi; I adjusted them from DHCP to 1.1.1.1 and 8.8.8.8 as an alternate and it has my containers running now.

Thank you for your attention, Tom, and wanted to let you know I am enjoying your text on PHP/MySQL thoroughly.
