### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Akpevwe11** [v-je/docker#7]
I ran into this issue while trying to build the image on Ubuntu: 
configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers
ERROR: `/tmp/pear/temp/xdebug/configure --with-php-config=/usr/local/bin/php-config' failed
The command '/bin/sh -c pecl install xdebug' returned a non-zero code: 1
ERROR: Service 'php' failed to build : Build failed

**Comment by RajeshKumarPadhy** [comment]
Edit PHP.dockerfile and change 
`RUN apk add --no-cache $PHPIZE_DEPS`

to 

`RUN apk add --no-cache $PHPIZE_DEPS`
`RUN apk add --no-cache linux-headers`

**Comment by TRPB** [comment]
Fixed by @RajeshKumarPadhy in https://github.com/v-je/docker/pull/8
